M48
; DRILL file {KiCad (6.0.11)} date Tue Jul 18 09:17:37 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-18T09:17:37+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X104.6Y-53.165
X104.6Y-146.225
X169.705Y-53.165
X169.705Y-146.225
T0
M30
